### ISSUE TITLE
presigned_url/4 Doesn't allow default overrides

### ISSUE THREAD

**Issue by BrendonPierson** [ex-aws/ex_aws_s3#2]
I am trying to specify a custom `X-Amz-Expires` value when generating a presigned_url for s3.  

Calling the function like this:
`presigned_url(:get, bucket, object, query_params: [{"X-Amz-Expires", 60 * 5}])`

Adds the query param, but also keeps the original.  I am getting a signatures mismatch when trying to use the link.  I believe this is because the request is signed before the query_params are added?

**Comment by simonme** [comment]
Hi, according to the docs, the expire time should be set with an `expires_in` param in the opts: https://hexdocs.pm/ex_aws/ExAws.S3.html#t:presigned_url_opts/0
```
presigned_url_opts() View Source
presigned_url_opts() :: [expires_in: integer, virtual_host: boolean, query_params: [{binary, binary}]]
```

Looking at the code, the original `expires` is added because the following params are set before any other query_params from the opts are added: https://github.com/ex-aws/ex_aws/blob/a87e89e5fd8fc47fe6f135dd93a133a05994b71b/lib/ex_aws/auth.ex#L204
```
  defp build_amz_query_params(service, datetime, config, expires) do
    [
      {"X-Amz-Algorithm",     "AWS4-HMAC-SHA256"},
      {"X-Amz-Credential",    Credentials.generate_credential_v4(service, config, datetime)},
      {"X-Amz-Date",          amz_date(datetime)},
      {"X-Amz-Expires",       expires},
      {"X-Amz-SignedHeaders", "host"},
    ] ++
    if config[:security_token] do
      [{"X-Amz-Security-Token", config[:security_token]}]
    else
      []
    end
  end
```

**Comment by benwilson512** [comment]
Indeed, expiration should be handled with the dedicated option. Also, query params are about URL query parameters not headers.

**Comment by tjshipe** [comment]
Can you set headers for a `presigned_url`? I'm looking to set the `response-content-disposition` header so I can set the file name when downloading from s3?
