### ISSUE TITLE
rm_rf/1 for directory removal.

### ISSUE THREAD

**Issue by jung-hunsoo** [ex-aws/ex_aws_s3#25]
I'm looking for an operation of s3 directory removal. Locally `File.rm_rf!/1` was used.

But unfortunately there seems no directory operations in `ex_aws_s3`.

If there's no direct way to do, then how about make a function that receive a path and remove all the files in it recursively? I think I can make a PR after some discussions.

**Comment by benwilson512** [comment]
Hey @jung-hunsoo, the main goal of the ExAws.S3 library is to provide an Elixir wrapper to the S3 API, and the S3 API does not have anything like `rm -rf`. This is in part because S3 doesn't actually have directories. However I think you can achieve what you want simply enough:

```
bucket = "some-bucket"

bucket
|> ExAws.S3.list_objects(prefix: "path/to/dir")
|> ExAws.stream!
|> Enum.map(fn %{key: key} ->
  bucket
  |> ExAws.delete_object(bucket,  key)
  |> ExAws.request!
end)
```

As you can see it's relatively simple to combine existing features from this library to achieve a lot of things.

**Comment by jung-hunsoo** [comment]
Thanks for response. Your comment was helpful enough to rewrite my own S3 policy.

Happily S3 prefix can be applied to `path + prefix_of_filename`. For example, `upload/images/8/89846b0a-8e62-4bd0-8e77-6e4e8d7a6af4_i1_original.jpg` and `upload/images/8/89846b0a-8e62-4bd0-8e77-6e4e8d7a6af4_i1_thumb.jpg` can be found by `list_objects(bucket, prefix: "upload/images/8/89846b0a-8e62-4bd0-8e77-6e4e8d7a6af4"`.

So I replaces the storage policy from folders of each UUID with folders of first character of UUID for better performance and readability.

And how about change some words in document? For example, `delete_object(bucket, object, opts \\ [])` can be `delete_object(bucket, object_key, opts \\ [])`. Because I confused to pass the `body.content` of list_objects/2`.
