### ISSUE TITLE
Support for mox

### ISSUE THREAD

**Issue by Den3** [ex-aws/ex_aws_s3#27]
Just wondering is it possible to add behaviour to each public API? I am trying to test my function that is integrated with this awesome library. Unfortunately, it does not have behaviour which means [mox](https://github.com/plataformatec/mox) can not mock it.

**Comment by benwilson512** [comment]
I don't think that'd be the right level to mock against. None of these functions actually hit AWS anyway, they return pure data structures. The real thing you want to mock is the `ExAws.request` function really.

**Comment by Den3** [comment]
Cool. Thank you for the explanation. I will figure out how to do that

**Comment by thbar** [comment]
Sharing in case it helps others (I will refactor our code otherwise): today I tried to add tests for existing code which uses unzip & ex_aws_s3, and in particular it would have been nice to have behaviours for other calls also leveraging `ExAws.request!`, like:

https://github.com/ex-aws/ex_aws_s3/blob/5096920bd2b2281723a27469565191bd66d3da0a/lib/ex_aws/s3/download.ex#L17

https://github.com/ex-aws/ex_aws_s3/blob/5096920bd2b2281723a27469565191bd66d3da0a/lib/ex_aws/s3/download.ex#L50

I wonder what can be done to make those calls more Moxable.

But maybe it is too low-level (I will wrap calls a step higher I think).
